### ISSUE TITLE
proposal - change aphrodite

### ISSUE THREAD

**Issue by b2whats** [jaredpalmer/react-production-starter#111]
https://github.com/jaredpalmer/react-production-starter/issues/60  - change on Jss ([benefits](https://github.com/cssinjs/jss/blob/master/docs/benefits.md#compared-to-aphrodite))

it does not have all those problems that are of Aphrodite, i can make PR if it need

**Comment by jaredpalmer** [comment]
@b2whats Will take a look.

**Comment by dlebedynskyi** [comment]
@jaredpalmer any sample on how to remove Aphrodite and use css-modules instead?

**Comment by jaredpalmer** [comment]
@dlebedynskyi sorry i don't. you'd need webpack-isomorphic-tools or something like it i think.

**Comment by jaredpalmer** [comment]
Going to go with `react-with-styles` and let people use whatever css-in-js they want.
