### ISSUE TITLE
client match with location vs history

### ISSUE THREAD

**Issue by djeeg** [jaredpalmer/react-production-starter#112]
routes and location are used here:
https://github.com/jaredpalmer/react-production-starter/blob/master/client/index.js#L33
`match({ routes, location }, (error, redirectLocation, renderProps) `

in this thread, taion says that routes and history should be used on the client
https://github.com/reactjs/react-router/issues/3290#issuecomment-209741339

does this cause any problems?

**Comment by jaredpalmer** [comment]
@djeeg I'm honestly not sure of the difference. 

Ryan Florence uses location here: https://github.com/ryanflorence/example-react-router-server-rendering-lazy-routes/blob/master/modules/client.js#L12

Feel free to submit a PR if you find a major difference in perf.

**Comment by jaredpalmer** [comment]
@djeeg did you figure out this issue with redial?
