### ISSUE TITLE
Dev Watch task

### ISSUE THREAD

**Issue by matiishyn** [jaredpalmer/react-production-starter#113]
Hello.

Could you please help me to create a watcher task for development.

I'm not good in React so not sure if it should be just watcher of Webpack or maybe it has something with HotReloader?

**Comment by jaredpalmer** [comment]
Could you be more specific? Hot Module Replacement works out of the box.

**Comment by matiishyn** [comment]
I run `npm start` which runs server that uses webpack with HMR, right?
In file: common/components/App.js, line:9 I'm changing the <h1> text. And after page refresh it's still the same. 
I have to run `npm start` again, and now I can see the new text in <h1>

Maybe it's a stupid question or I'm doing something wrong. Sorry about that

**Comment by jaredpalmer** [comment]
Just fixed the issue. Had tried to get clean up server.js use of assets.json during dev, but created a race condition. Pull master. Or make these changes: https://github.com/jaredpalmer/react-production-starter/commit/d7a34e6585dfc38a4b424925e7ce9e959f615036

You can also remove assets-plugin from dev. will make that change now in master.
