### ISSUE TITLE
proposal - change from Axios to isomorphic-fetch

### ISSUE THREAD

**Issue by misterfresh** [jaredpalmer/react-production-starter#118]
Fetch is a standard. Maybe I'm missing something but I don't see the upside of using Axios.

**Comment by jaredpalmer** [comment]
I like fetch, but I also like the ability to configure multiple axios clients with headers and tokens etc.. I also like that I don't need to transform to json() everywhere. These are my opinions, of course.

Additionally, it is pretty simple to just swap out axios for isomorphic-fetch. If you do this, I suggest importing fetch once in `store.js` and then just passing it through to all your actions via [`thunk.withExtraArgument`](https://github.com/jaredpalmer/react-production-starter/blob/master/common/store.js#L9). You can also create a custom `callAPIMiddleware`, although I personally think these make testing more difficult.
