### ISSUE TITLE
Ajax requests

### ISSUE THREAD

**Issue by couturecraigj** [jaredpalmer/react-production-starter#120]
I love this layout by the way it is by far one of the better laid out boilerplates out there.

I am wondering with the current setup how one would send Ajax requests since you might not want certain things to be part of the server side rendering.  Any ideas... Examples of this might be comments as that may be in another table.

**Comment by jaredpalmer** [comment]
You should read up on `redial`. However, you can always leverage `componentDidMount()` which will only run on the client.

**Comment by jaredpalmer** [comment]
Thanks for the compliment!

**Comment by begoat** [comment]
@jaredpalmer  hello, could you please explain more about the sentence below?
> You should read up on redial.

I didn't get it :)
