### ISSUE TITLE
Combine Reducer error

### ISSUE THREAD

**Issue by ericmasiello** [jaredpalmer/react-production-starter#135]
This may not be anything important but I noticed if I run the app using `npm start` and then visit a page such as http://localhost:5000/post/hows-business-boomin - everything works fine. However, if I have Chrome DevTools open and now refresh the browser on that page, I see the following error:

```
combineReducers.js:29 Unexpected property "currentPost" found in previous state received by the reducer. Expected to find one of the known reducer property names instead: "sourceRequest". Unexpected properties will be ignored.
(anonymous function) @ combineReducers.js:29
o @ VM6299:1
i @ VM6299:1
(anonymous function) @ VM6299:1
dispatch @ createStore.js:179
createStore @ createStore.js:254
(anonymous function) @ VM6299:1
(anonymous function) @ VM6299:1
(anonymous function) @ VM6299:1
(anonymous function) @ applyMiddleware.js:38
createStore @ createStore.js:65
configureStore @ store.js:29
(anonymous function) @ index.js:39
(anonymous function) @ main.js:89
__webpack_require__ @ vendor.js:586
fn @ vendor.js:110
(anonymous function) @ multi_main:3
(anonymous function) @ main.js:5
__webpack_require__ @ vendor.js:586
webpackJsonpCallback @ vendor.js:22
(anonymous function) @ main.js:1
```
Any idea what's causing this?

**Comment by jaredpalmer** [comment]
See #86 . This is a known bug. 

I think it has to do with how the server injects reducers on first load and then `injectAsyncReducer`   merges (the exact same reducer) on the client (again). It doesn't actually affect anything and there isn't an extra request sent. Just an eyesore in the console tbh.

**Comment by ericmasiello** [comment]
Thanks!
