### ISSUE TITLE
Immutable.toJs in mapping props is fatal for production apps

### ISSUE THREAD

**Issue by R0bson** [jaredpalmer/react-production-starter#136]
In routes/Post/reducer.js is method:
`export const selectCurrentPost = state => state.get('currentPost').toJS()`
which later is used by PostPage container in mapping state to props.

This mapping occurs on every update of state and it is simply expensive... In such small app it isn't an issue, but introducing such a **pattern for production app** (like a name of a starter) will have fatal impact for future performance.

Also mapping to js is wasting possibility to make component pure with easy checking in shouldComponentUpdate. With Immutable it is plain easy, but when component receives JS object it is again hard task.

Tweet of Lee Byron, main creator of Immutable.js about toJS performance:
https://twitter.com/leeb/status/746733697093668864

If immutablejs is used only to ensure Redux state's immutability then eg. https://github.com/substantial/updeep would be a better. Immutablejs offers more 'power' for optimizations, but.. power comes with responsibility ;)

**Comment by jaredpalmer** [comment]
Wow. Didn't know that. 

Let's drop it then. 

If you have time to submit a PR, that would be huge.

**Comment by R0bson** [comment]
Here you go: #137

**Comment by kishorevarma** [comment]
IMHO @R0bson thats a good point, but we can use [reselect] (https://github.com/reactjs/reselect/) to solve that issue and I agree we shouldn't convert the immutable to JS

**Comment by R0bson** [comment]
@kishorevarma Sure! reselect is great option to gather data from immutable. Anyway it still requires to be selected in render() and not in mapping to props. Otherwise it would be impossible to get free optimization of shallow comparing by extending React.PureComponent instead React.Component.

@kishorevarma Do you have any good practices on using reselect with immutable. Something unrelated to specific project and what could be introduced as good pattern for starter?

**Comment by kishorevarma** [comment]
Hope following will help 
[https://github.com/reactjs/reselect/#q-how-do-i-use-reselect-with-immutablejs](https://github.com/reactjs/reselect/#q-how-do-i-use-reselect-with-immutablejs)
