### ISSUE TITLE
Add some babel plugin

### ISSUE THREAD

**Issue by oliviertassinari** [jaredpalmer/react-production-starter#17]
What do you think about those plugins?
https://github.com/FormidableLabs/spectacle/pull/154

**Comment by jaredpalmer** [comment]
Constant and inline are good. 

Other thing you can do is pull ReactDOMServer from minified react. 

Haven't tried it, but with `react-dom-stream` you could potentially get TTFB to sub 50ms.

**Comment by jaredpalmer** [comment]
#25
