### ISSUE TITLE
First time clicking on "Example Feed" link in Nav does to load posts. You need to click the link twice for data to show up.

### ISSUE THREAD

**Issue by seanyesmunt** [jaredpalmer/react-production-starter#172]
After doing `npm i && npm start` the page loads fine, but when I go to click the "Example Feed" link, the posts do not show and the `loadPosts` action is never dispatched. If I click it a second time, the data is loaded.

**Comment by jaredpalmer** [comment]
Yeah. It looks like an issue with react-router v3. Need to do some more investigation on this
