### ISSUE TITLE
React Router v3

### ISSUE THREAD

**Issue by jaredpalmer** [jaredpalmer/react-production-starter#174]
Fix issue #172

**Comment by jaredpalmer** [comment]
cc @seanyesmunt

**Comment by seanyesmunt** [comment]
Any idea of when you will be able to look into this? I might be able to give it a try if you think it will be a while.

**Comment by jaredpalmer** [comment]
very very shortly (like over the weekend maybe). About to start on a 50+ route app with this. 

Short Term Goals: make a better boilerplate
- react router 3, or v4 with an addon
- webpack 2 beta, transpile the server
- chokidar to watch server folder for changes, and handle restarts
- drop redial for redux-taxi, so you can declare data at component level instead of at the route level
- decide on glamor vs. aphrodite
- a client-only prototype env and npm script
- react-storybook
- jest, ava
- docs

Long Term Goals: wrap this up into a framework + cli

**Comment by seanyesmunt** [comment]
Looks awesome, v4 react router would be sweet! Thanks

**Comment by jaredpalmer** [comment]
@seanyesmunt are you using this kit at Walmart?

**Comment by seanyesmunt** [comment]
@jaredpalmer No, just using it for a side project I am working on with a friend. https://github.com/seanyesmunt/universal-js

**Comment by jaredpalmer** [comment]
Closing this. Moving to 4. #212
