### ISSUE TITLE
Add example of a form where state is managed by redux?

### ISSUE THREAD

**Issue by walshe** [jaredpalmer/react-production-starter#182]
I've been looking at a few:  redux-ui, redux-form and react-redux-form but as a redux newb I'm finding it so hard to integrate into this seed...

would be great to see an example..

**Comment by jaredpalmer** [comment]
I highly advise against using redux to manage form state unless you need to persist it to localStorage.

**Comment by walshe** [comment]
fair enough, 

any chance of adding some sort of form example in there at some stage ?

**Comment by youmustfight** [comment]
+1, but also why is managing form state with redux a bad idea? Is it because it clutters the store, or because you think it's better to manage on a component level? (PS: Also a React/Redux newb)
