### ISSUE TITLE
Unexpected key "currentPost"

### ISSUE THREAD

**Issue by Arueilen** [jaredpalmer/react-production-starter#27]
Hi, I found your boilerplate yesterday and it seems very cool !
But I have a bug when I want to run your example.
When I go to http://0.0.0.0:5000/ all works fine.
But if I go to http://0.0.0.0:5000/post/hows-business-boomin and then refresh the page, I have some errors into my Chrome and Firefox inspector: 
- Unexpected key "currentPost" found in initialState argument passed to createStore. Expected to find one of the known reducer keys instead: "posts". Unexpected keys will be ignored.
- Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) <noscript data-reacti
 (server) <div class="root_fpza

I think it's a bug relate to asynchronous reducers. Why do you want asynchronous reducers ?

**Comment by LASkuma** [comment]
Asyn reducers are used for code splitting.

**Comment by jaredpalmer** [comment]
Fixed.
