### ISSUE TITLE
Hot Reload not working?

### ISSUE THREAD

**Issue by donaldpipowitch** [jaredpalmer/react-production-starter#29]
The first time I heard about hot reloading I was so euphoric, but since when ever I try to test it in an open source project, it doesn't seem to work. Can you verify that this doesn't work or do I use it wrong?

I followed the installation guide from the README.md. I called `$ npm start`. This should start watching the source files and hot reloading, right? I then changed [this line](https://github.com/jaredpalmer/react-production-starter/blob/master/src/components/Nav.js#L12) from `Home` to `Home2`. I'd expect to see `Home2` now in my browser after re-compiling, but I only get a warning in the console:

```
[HMR] The following modules couldn't be hot updated: (Full reload needed)
This is usually because the modules which have changed (and their parents) do not know how to hot reload themselves. See http://webpack.github.io/docs/hot-module-replacement-with-webpack.html for more details.
[HMR]  - ./src/components/Nav.js
```

**Comment by jaredpalmer** [comment]
Will look into this in more detail later tonight. For now, just write the components you want to have HMR as classes instead of stateless components.

```javascript
class Blah extends React.component {...}
```

**Comment by jaredpalmer** [comment]
So i have explored this since Dan Abramov recently announced the sunsetting of react-transform and suggested its removal from some of the redux examples. On a local branch, I implement vanilla HMR with webpack using the suggested technique. I can submit a PR.

**Comment by nesbtesh** [comment]
So hot reloading doesnt work for extended templates? For example this works in create react app but doesnt work in razzle:

 export default class Collection extends MainTemplate {
