### ISSUE TITLE
Use Throng

### ISSUE THREAD

**Issue by jaredpalmer** [jaredpalmer/react-production-starter#41]
I personally think [pm2](https://github.com/Unitech/pm2) is overkill. [Throng](https://github.com/hunterloftis/throng) is a super lightweight wrapper around `cluster` written by Heroku's Hunter Loftis. We use it in production at ShellyPalmer. It's rock solid. 

Edit: added links to pm2 and throng

**Comment by b2whats** [comment]
pm2 - it's https://github.com/Unitech/pm2 ?

**Comment by jaredpalmer** [comment]
Correct

**Comment by ranyefet** [comment]
I didn't know about Throng before but I agree that it's better to start with simpler solution :+1:
