### ISSUE TITLE
Update to React 15.0.1

### ISSUE THREAD

**Issue by rowellx68** [jaredpalmer/react-production-starter#44]
@jaredpalmer what are your thoughts about updating this to React 15.0.1?

**Comment by gihrig** [comment]
I have updated all packages to latest (including React 15.0.2) and all seems to be well. All build and test operations work as expected and no app errors have been observed.

I used `npm install package1@* package2@* etc@* --save` but [npm-check-updates](https://www.npmjs.com/package/npm-check-updates) looks to make this even easier.
