### ISSUE TITLE
Clean up webpack files

### ISSUE THREAD

**Issue by jaredpalmer** [jaredpalmer/react-production-starter#55]
Use config vars instead of hard coding the build directory.

**Comment by b2whats** [comment]
this is good idea, see my webpack config

it may be worth it to replace generate markup in server.js file and asset plugin on new HTMLWebpackPlugin ?

also https://github.com/jaredpalmer/react-production-starter/blob/master/webpack.config.dev.js#L11
https://github.com/glenjamin/webpack-hot-middleware#changelog
