### ISSUE TITLE
Add ImmutableJS

### ISSUE THREAD

**Issue by jaredpalmer** [jaredpalmer/react-production-starter#61]

**Comment by rowellx68** [comment]
Where do you intend to use ImmutableJS?

**Comment by jaredpalmer** [comment]
Reducers.

**Comment by rowellx68** [comment]
Something like this?

https://github.com/rowellx68/react-production-starter/blob/a6e2b2ff220f1255fc98821cc13c97b5b4baa5ed/common/routes/Post/reducer.js

**Comment by jaredpalmer** [comment]
Yup.
