### ISSUE TITLE
shortest route (without static prefix-path) not working

### ISSUE THREAD

**Issue by bbnnt** [jaredpalmer/react-production-starter#69]
The posts route here (https://github.com/jaredpalmer/react-production-starter/blob/master/src/routes/Post/index.js#L6) show posts/:slug, slug being dynamic

I was looking into having a short one, like "http://domain.stuff/my-post-slug", which would translate to `path: ':slug'` at the same spot. Thing is, no way to make it work that short

Using the same with regular routing (not ssr and no dynamic redux routes loading), it works without problem. But I just can't see how to solve this in those fields — sorry if the answer is obvious; but thx a lot if it exists !

(ps thx a lot for the patterns and arch exposed in this repo! best work found)

**Comment by jaredpalmer** [comment]
Just tried this out. You'll have to basically handle not found errors in your PostPage because `:slug`

**Comment by jaredpalmer** [comment]
Don't forget to change the `<Link />` in `<PostListItem />`.

**Comment by bbnnt** [comment]
sorry i closed and reopened but… it does work pretty okay on your repo (changing path and url in the list component). i tweaked this repo a bit, the problem happened when requiring images (src was an object, instead of being inlined as source uri). i guess i have to check a bit more what's to be done in webpack
