### ISSUE TITLE
kube?

### ISSUE THREAD

**Issue by uptownhr** [jaredpalmer/react-production-starter#83]
I saw you starred kube recently. I would really love to hear your thoughts on it.

**Comment by jaredpalmer** [comment]
Haven't fully evaluated live, but I am really interested in hyperbova. However, haven't yet gotten it working. As soon as I do, expect a hypernova starter

**Comment by jaredpalmer** [comment]
Haven't fully evaluated live, but I am really interested in hyperbova. However, haven't yet gotten it working. As soon as I do, expect a hypernova starter

**Comment by jaredpalmer** [comment]
Apologies for horrible spelling mistakes.....at the clubbbbb :fire:

**Comment by uptownhr** [comment]
no worries have fun. hypernova looks pretty cool. tackling some of the same
problems. does it also handle hmr?
