### ISSUE TITLE
unexpected key "posts"

### ISSUE THREAD

**Issue by tagraha** [jaredpalmer/react-production-starter#86]
Everything works fine when i'm navigate from localhost:5000 but my console giving an error if I navigate directly (or refresh) localhost:5000/posts. however.. the app's still works fine even with an error on my console. is it okay to ignore that error? 

![posts](https://cloud.githubusercontent.com/assets/3034375/16161119/09ade334-34f6-11e6-98db-ecd2d9d3526d.png)

**Comment by jaredpalmer** [comment]
See #38

**Comment by jaredpalmer** [comment]
It's just a warning
