### ISSUE TITLE
Project Name Change

### ISSUE THREAD

**Issue by jaredpalmer** [jaredpalmer/react-production-starter#90]
`React-boilerplate` (the most popular react boilerplate on github) is struggling to implement ssr. Obviously, that's this project's bread and butter. Wondering if it makes sense to rename this project, `react-boilerplate-ssr` to increase discoverability.

Any other ideas? Objections? Comments?

**Comment by developerwok** [comment]
I think its a tactic that works in nature, exposure by association. I've gone through 4 or 5 boilerplates to learn react and redux.  I think i found your project here http://andrewhfarmer.com/starter-project/ Writing a medium article and  guide for server side rendering would probably help with exposure.
