### ISSUE TITLE
Using in nitrous.io

### ISSUE THREAD

**Issue by bresson** [jaredpalmer/react-production-starter#97]
Repo appears to start fine with 'npm start,' however the terminal returns the following error:

ERROR in ./client/index.js
Module parse failed: /home/nitrous/code/react-server-boilerplate/node_modules/standard-loader/index.js!/home/nitrous/code/react-server-boilerplate/client/index
.js Unexpected token (37:6)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (37:6)

**Comment by jaredpalmer** [comment]
Hmm. Never tried on nitrous. Will explore

**Comment by kentendo** [comment]
I just cloned master and am having this issue now.
